# Generated by Django 5.2.13 on 2026-04-28 04:33

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=5, unique=True, verbose_name='Codigo/sku')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Mercadoria')),
                ('estoque', models.IntegerField(default=0, verbose_name='Estoque Atual')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Compra')),
                ('perc_imposto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual de Imposto (%)')),
                ('perc_varejo', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual de Margem de Lucro para Varejo (%)')),
                ('perc_atacado', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual de Margem de Lucro para Atacado (%)')),
                ('valor_venda_varejo', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('valor_venda_atacado', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cargo', models.CharField(choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor')], default='vendedor', max_length=20, verbose_name='Cargo')),
                ('comissao', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual de Comissão (%)')),
                ('matricula', models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='ID de acesso')),
                ('usuario', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_vendida', models.PositiveIntegerField(verbose_name='Quantidade Vendida')),
                ('tipo_venda', models.CharField(choices=[('varejo', 'Varejo'), ('atacado', 'Atacado')], max_length=20, verbose_name='Tipo de Venda')),
                ('forma_pagamento', models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('credito', 'Crédito'), ('debito', 'Débito'), ('credito_pix', 'Crédito + Pix'), ('credito_dinheiro', 'Crédito + Dinheiro'), ('credito_debito', 'Crédito + Débito'), ('debito_pix', 'Débito + Pix'), ('debito_dinheiro', 'Débito + Dinheiro'), ('dinheiro_pix', 'Dinheiro + Pix')], default='dinheiro', max_length=50, verbose_name='Forma de Pagamento')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('preco_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço Total')),
                ('comissao_aplicada', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('valor_comissao', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
                ('vendedor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
            ],
        ),
        migrations.CreateModel(
            name='EstoqueVendedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_atual', models.IntegerField(default=0, verbose_name='Quantidade com o Vendedor')),
                ('vendedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto', verbose_name='Mercadoria')),
            ],
            options={
                'verbose_name': 'Estoque do Vendedor',
                'verbose_name_plural': 'Estoques dos Vendedores',
                'unique_together': {('vendedor', 'produto')},
            },
        ),
    ]
