# Generated by Django 5.2.13 on 2026-04-23 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=50, unique=True, verbose_name='Referência')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Mercadoria')),
                ('quantidade', models.IntegerField(default=0, verbose_name='Estoque Atual')),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor de Compra')),
                ('per_imposto', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual de Imposto (%)')),
                ('valor_venda_varejo', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
                ('valor_venda_atacado', models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True)),
            ],
        ),
    ]
