# Generated by Django 5.2.13 on 2026-04-28 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='referencia',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='Codigo/sku'),
        ),
    ]
