# Generated by Django 5.2.13 on 2026-04-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='per_imposto',
            new_name='perc_imposto',
        ),
        migrations.AddField(
            model_name='produto',
            name='perc_atacado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual de Margem de Lucro para Atacado (%)'),
        ),
        migrations.AddField(
            model_name='produto',
            name='perc_varejo',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual de Margem de Lucro para Varejo (%)'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='referencia',
            field=models.CharField(max_length=50, unique=True, verbose_name='Codigo/sku'),
        ),
    ]
