# Generated by Django 5.2.13 on 2026-04-23 19:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0002_rename_per_imposto_produto_perc_imposto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='produto',
            old_name='quantidade',
            new_name='estoque',
        ),
    ]
