# Generated by Django 5.2.13 on 2026-04-23 20:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_rename_quantidade_produto_estoque'),
    ]

    operations = [
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade_vendida', models.PositiveIntegerField(verbose_name='Quantidade Vendida')),
                ('tipo_venda', models.CharField(choices=[('varejo', 'Varejo'), ('atacado', 'Atacado')], max_length=20, verbose_name='Tipo de Venda')),
                ('data_venda', models.DateTimeField(auto_now_add=True, verbose_name='Data da Venda')),
                ('preco_total', models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço Total')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto')),
            ],
        ),
    ]
