# Generated by Django 5.2.13 on 2026-05-03 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0003_perfil_cor_banner_perfil_data_nascimento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfil',
            name='cor_banner',
            field=models.CharField(blank=True, default='#1E294A', max_length=10, null=True),
        ),
    ]
