# Generated by Django 5.2.13 on 2026-05-04 01:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_alter_perfil_cor_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'verbose_name': 'Perfil de Usuário', 'verbose_name_plural': 'Perfis de Usuários'},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'verbose_name': 'Produto', 'verbose_name_plural': 'Produtos'},
        ),
        migrations.AlterModelOptions(
            name='venda',
            options={'verbose_name': 'Venda', 'verbose_name_plural': 'Vendas'},
        ),
        migrations.AlterField(
            model_name='perfil',
            name='cor_banner',
            field=models.CharField(blank=True, default='#1E294A', max_length=10, null=True, verbose_name='Cor do Banner (Hex)'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de Nascimento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='endereco',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Endereço'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='avatares/', verbose_name='Foto de Perfil'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='matricula',
            field=models.CharField(blank=True, max_length=5, null=True, unique=True, verbose_name='ID de Acesso (Matrícula)'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='telefone',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='Telefone'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_venda_atacado',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Preço de Atacado'),
        ),
        migrations.AlterField(
            model_name='produto',
            name='valor_venda_varejo',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, null=True, verbose_name='Preço de Varejo'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='comissao_aplicada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Comissão Aplicada (%)'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='preco_total',
            field=models.DecimalField(decimal_places=2, editable=False, max_digits=10, verbose_name='Preço Total da Venda'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='produto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='loja.produto', verbose_name='Produto'),
        ),
        migrations.AlterField(
            model_name='venda',
            name='valor_comissao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor da Comissão (R$)'),
        ),
    ]
