# Generated by Django 5.2.13 on 2026-04-26 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0004_venda'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome do Perfil')),
                ('cargo', models.CharField(choices=[('administrador', 'Administrador'), ('vendedor', 'Vendedor')], default='vendedor', max_length=20, verbose_name='Cargo')),
                ('comissao', models.DecimalField(decimal_places=2, default=0.0, help_text='Percentual de comissão.', max_digits=5, verbose_name='Percentual de Comissão (%)')),
            ],
        ),
        migrations.AddField(
            model_name='venda',
            name='comissao_aplicada',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_comissao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='venda',
            name='vendedor',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Vendedor'),
        ),
    ]
