# Generated by Django 5.2.13 on 2026-05-04 03:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_alter_perfil_options_alter_produto_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricoPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_alteracao', models.DateTimeField(auto_now_add=True)),
                ('valor_compra', models.DecimalField(decimal_places=2, max_digits=10)),
                ('perc_imposto', models.DecimalField(decimal_places=2, max_digits=5)),
                ('perc_varejo', models.DecimalField(decimal_places=2, max_digits=5)),
                ('perc_atacado', models.DecimalField(decimal_places=2, max_digits=5)),
                ('quantidade_adicionada', models.IntegerField()),
                ('estoque_final', models.IntegerField()),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historicos', to='loja.produto')),
            ],
            options={
                'verbose_name': 'Histórico de Preço e Estoque',
                'verbose_name_plural': 'Históricos de Preços e Estoques',
                'ordering': ['-data_alteracao'],
            },
        ),
    ]
