# Generated by Django 5.2.13 on 2026-04-26 18:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0005_perfil_venda_comissao_aplicada_venda_valor_comissao_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='perfil',
            name='nome',
        ),
        migrations.AddField(
            model_name='perfil',
            name='usuario',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='venda',
            name='forma_pagamento',
            field=models.CharField(choices=[('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('credito', 'Crédito'), ('debito', 'Débito'), ('credito_pix', 'Crédito + Pix'), ('credito_dinheiro', 'Crédito + Dinheiro'), ('credito_debito', 'Crédito + Débito'), ('debito_pix', 'Débito + Pix'), ('debito_dinheiro', 'Débito + Dinheiro'), ('dinheiro_pix', 'Dinheiro + Pix')], default='dinheiro', max_length=50, verbose_name='Forma de Pagamento'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='comissao',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Percentual de Comissão (%)'),
        ),
    ]
