# Generated by Django 5.2.13 on 2026-05-05 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0006_historicopreco'),
    ]

    operations = [
        migrations.AddField(
            model_name='venda',
            name='bandeira_cartao',
            field=models.CharField(blank=True, choices=[('visa', 'Visa'), ('master', 'Mastercard'), ('hiper', 'Hipercard'), ('elo', 'Elo'), ('outra', 'Outra')], max_length=20, null=True, verbose_name='Bandeira do Cartão'),
        ),
    ]
