# Generated by Django 5.2.13 on 2026-06-07 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_venda_bandeira_cartao'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='em_promocao',
            field=models.BooleanField(default=False, verbose_name='Em Promoção'),
        ),
        migrations.AddField(
            model_name='venda',
            name='desconto_aplicado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Desconto Aplicado (%)'),
        ),
        migrations.AddField(
            model_name='venda',
            name='em_promocao',
            field=models.BooleanField(default=False, verbose_name='Em Promoção'),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_credito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor no Crédito'),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_debito',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor no Débito'),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_dinheiro',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor no Dinheiro'),
        ),
        migrations.AddField(
            model_name='venda',
            name='valor_pix',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Valor no Pix'),
        ),
        migrations.AlterField(
            model_name='perfil',
            name='foto',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to='avatares/', verbose_name='Foto de Perfil'),
        ),
    ]
