# Generated by Django 5.2.13 on 2026-04-26 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loja', '0007_estoquevendedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produto',
            name='referencia',
            field=models.CharField(max_length=5, unique=True, verbose_name='Codigo/sku'),
        ),
    ]
